{
	"openapi": "3.0.0",
	"info": {
		"title": "API de informações de Clínicas e Hospitais",
		"description": "Sobre a API de Clínicas e Hospitais",
		"contact": {
			"email": "ericspsantos@gmail.com"
		},
		"version": "1.0.0"
	},
	"servers": [
		{
			"url": "http://localhost:5000",
			"description": "API WEB SAÚDE local"
		},
		{
			"url": "https://api-web-saude.vercel.app/",
			"description": "API WEB SAÚDE hospedada"
		  }
	],
	"paths": {
		"/login": {
		  "post": {
			"summary": "Autenticar usuário",
			"tags": ["Usuarios"],
			"requestBody": {
			  "required": true,
			  "content": {
				"application/json": {
				  "schema": {
					"$ref": "#/components/schemas/Login"
				  }
				}
			  }
			},
			"responses": {
			  "200": {
				"description": "Autenticação bem-sucedida",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"token": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  },
			  "401": {
				"description": "Login não autorizado",
				"content": {
				  "application/json": {
					"schema": {
					  "$ref": "#/components/schemas/Login"
					}
				  }
				}
			  },
			  "500": {
				"description": "Erro interno do servidor"
			  }
			}
		  }
		},
		"/usuario/novo-usuario": {
		  "post": {
			"summary": "Cadastrar Usuário",
			"description": "Essa rota será responsável por cadastrar um usuário",
			"tags": ["Usuarios"],
			"security": [
			  {
				"bearerAuth": []
			  }
			],
			"requestBody": {
			  "description": "Dados do Usuário",
			  "required": true,
			  "content": {
				"application/json": {
				  "schema": {
					"$ref": "#/components/schemas/Usuario"
				  }
				}
			  }
			},
			"responses": {
			  "201": {
				"description": "Usuário cadastrado com Sucesso!",
				"content": {
				  "application/json": {
					"schema": {
					  "$ref": "#/components/schemas/Usuario"
					}
				  }
				}
			  },
			  "400": {
				"description": "Campos inválidos ou nome muito curto",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						},
						"Errors": {
						  "type": "array",
						  "items": {
							"type": "string"
						  }
						}
					  }
					}
				  }
				}
			  },
			  "500": {
				"description": "Erro interno do servidor",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  }
			}
		  }
		},
		"/usuario/alterar-usuario/{id}": {
		  "put": {
			"summary": "Alterar Usuário",
			"description": "Essa rota será responsável por alterar um usuário existente",
			"tags": ["Usuarios"],
			"security": [
			  {
				"bearerAuth": []
			  }
			],
			"parameters": [
			  {
				"name": "id",
				"in": "path",
				"required": true,
				"schema": {
				  "type": "string"
				},
				"description": "ID do usuário a ser alterado"
			  }
			],
			"requestBody": {
			  "description": "Dados atualizados do Usuário",
			  "required": true,
			  "content": {
				"application/json": {
				  "schema": {
					"$ref": "#/components/schemas/Usuario"
				  }
				}
			  }
			},
			"responses": {
			  "200": {
				"description": "Usuário alterado com sucesso",
				"content": {
				  "application/json": {
					"schema": {
					  "$ref": "#/components/schemas/Usuario"
					}
				  }
				}
			  },
			  "400": {
				"description": "Campos inválidos ou nome muito curto",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						},
						"Errors": {
						  "type": "array",
						  "items": {
							"type": "string"
						  }
						}
					  }
					}
				  }
				}
			  },
			  "500": {
				"description": "Erro interno do servidor",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  }
			}
		  }
		},
		"/usuario/deletar-usuario/{id}": {
		  "delete": {
			"summary": "Deletar Usuário",
			"description": "Essa rota será responsável por deletar um usuário existente",
			"tags": ["Usuarios"],
			"security": [
			  {
				"bearerAuth": []
			  }
			],
			"parameters": [
			  {
				"name": "id",
				"in": "path",
				"required": true,
				"schema": {
				  "type": "string"
				},
				"description": "ID do usuário a ser deletado"
			  }
			],
			"responses": {
			  "204": {
				"description": "Usuário deletado com sucesso"
			  },
			  "404": {
				"description": "Usuário não encontrado",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  },
			  "500": {
				"description": "Erro interno do servidor",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  }
			}
		  }
		},
		"/usuario/usuarios": {
		  "get": {
			"summary": "Listar Usuários",
			"description": "Esta rota lista todos os usuários",
			"tags": ["Usuarios"],
			"responses": {
			  "200": {
				"description": "Usuários listados com sucesso.",
				"content": {
				  "application/json": {
					"schema": {
					  "$ref": "#/components/schemas/Usuario"
					}
				  }
				}
			  },
			  "404": {
				"description": "Nenhum usuário encontrado",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  },
			  "500": {
				"description": "Erro interno do servidor",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  }
			}
		  }
		},
		"/usuario/usuario/nova-senha/{nome}": {
		  "put": {
			"summary": "Alterar Senha do Usuário",
			"description": "Esta rota permite que o usuário altere sua senha",
			"tags": ["Usuarios"],
			"parameters": [
			  {
				"name": "nome",
				"in": "path",
				"required": true,
				"schema": {
				  "type": "string"
				},
				"description": "Nome do usuário"
			  }
			],
			"requestBody": {
			  "description": "Nova Senha do Usuário",
			  "required": true,
			  "content": {
				"application/json": {
				  "schema": {
					"$ref": "#/components/schemas/Senha"
				  }
				}
			  }
			},
			"responses": {
			  "200": {
				"description": "Senha alterada com sucesso",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"mensagem": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  },
			  "400": {
				"description": "Campos inválidos ou senhas não coincidem",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						},
						"Errors": {
						  "type": "array",
						  "items": {
							"type": "string"
						  }
						}
					  }
					}
				  }
				}
			  },
			  "500": {
				"description": "Erro interno do servidor",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  }
			}
		  }
		},
		"/usuario/usuario/unidades-de-saude/": {
		  "get": {
			"summary": "Listar Unidades de Saúde do Usuário",
			"description": "Esta rota lista todas as unidades de saúde associadas ao usuário",
			"tags": ["Usuarios"],
			"responses": {
			  "200": {
				"description": "Unidades de Saúde listadas com sucesso.",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "array",
					  "items": {
						"$ref": "#/components/schemas/UnidadeDeSaude"
					  }
					}
				  }
				}
			  },
			  "404": {
				"description": "Nenhuma unidade de saúde encontrada para o usuário",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  },
			  "500": {
				"description": "Erro interno do servidor",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  }
			}
		  }
		},
		"/usuario/usuario/{nome}": {
		  "get": {
			"summary": "Pegar Usuário pelo Nome",
			"description": "Esta rota retorna informações do usuário pelo nome",
			"tags": ["Usuarios"],
			"parameters": [
			  {
				"name": "nome",
				"in": "path",
				"required": true,
				"schema": {
				  "type": "string"
				},
				"description": "Nome do usuário"
			  }
			],
			"responses": {
			  "200": {
				"description": "Usuário encontrado com sucesso.",
				"content": {
				  "application/json": {
					"schema": {
					  "$ref": "#/components/schemas/Usuario"
					}
				  }
				}
			  },
			  "404": {
				"description": "Usuário não encontrado",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  },
			  "500": {
				"description": "Erro interno do servidor",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"Message": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  }
			}
		  }
		},
		"/usuario/total-usuarios": {
		  "get": {
			"summary": "Obter Total de Usuários",
			"description": "Esta rota retorna o total de usuários cadastrados",
			"tags": ["Usuarios"],
			"responses": {
			  "200": {
				"description": "Total de usuários obtido com sucesso.",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"total": {
						  "type": "integer"
						}
					  }
					}
				  }
				}
			  },
			  "500": {
				"description": "Erro interno do servidor",
				"content": {
				  "application/json": {
					"schema": {
					  "type": "object",
					  "properties": {
						"error": {
						  "type": "string"
						}
					  }
					}
				  }
				}
			  }
			}
		  
			}
		},
		"/admin/nova-clinica": {
			"post": {
				"summary": "Cadastrar Clínica",
				"description": "Essa rota será responsável por cadastrar uma clínica",
				"tags": ["Clinicas"],
				"security": [
					{
						"bearerAuth": []
					}
				],
				"requestBody": {
					"description": "Dados da Clínica",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/Clinica"
							},
							"examples": {
								"clinica": {
									"value": {
										"cep": "00000-000",
										"rua": "rua x",
										"numero": 123,
										"bairro": "bairro x",
										"cidade": "cidade x",
										"uf": "xx",
										"nome": "Clinica x",
										"imagem": "url_da_imagem",
										"horarioSemana": {
											"open": "08:00",
											"close": "17:00"
										},
										"Sabado": {
											"open": "09:00",
											"close": "13:00"
										},
										"longitude": -43.123456,
										"latitude": -22.987654,
										"especialidades": [
											"id_especialidade_1",
											"id_especialidade_2"
										],
										"instagram": "perfil_instagram",
										"email": "email@clinica.com",
										"whatsapp": "+55 11 1234-5678",
										"descricao": "Descrição da clínica"
									}
								}
							}
						}
					}
				},
				"responses": {
					"201": {
						"description": "Clínica salva com Sucesso!",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Clinica"
								},
								"examples": {
									"clinica": {
										"value": {
											"nome": "Clinica X",
											"imagem": "url_da_imagem",
											"horarioSemana": {
												"open": "08:00",
												"close": "17:00"
											},
											"Sabado": {
												"open": "09:00",
												"close": "13:00"
											},
											"longitude": -43.123456,
											"latitude": -22.987654,
											"especialidades": [
												"id_especialidade_1",
												"id_especialidade_2"
											],
											"instagram": "perfil_instagram",
											"email": "email@clinica.com",
											"whatsapp": "+55 11 1234-5678",
											"descricao": "Descrição da clínica",
											"endereco": "id_endereco"
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "Campos inválidos ou nome muito curto",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										},
										"Errors": {
											"type": "array",
											"items": {
												"type": "string"
											}
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno do servidor",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/admin/alterar-clinica/{id}": {
			"put": {
				"summary": "Alterar Clínica",
				"description": "Essa rota será responsável por alterar uma clínica existente",
				"tags": ["Clinicas"],
				"security": [
					{
						"bearerAuth": []
					}
				],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"description": "ID da clínica a ser alterada"
					}
				],
				"requestBody": {
					"description": "Dados atualizados da Clínica",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/Clinica"
							},
							"examples": {
								"clinica": {
									"value": {
										"nome": "Clinica X Atualizada",
										"imagem": "url_da_imagem_atualizada",
										"horarioSemana": {
											"open": "09:00",
											"close": "18:00"
										},
										"Sabado": {
											"open": "10:00",
											"close": "14:00"
										},
										"longitude": -43.123456,
										"latitude": -22.987654,
										"especialidades": [
											"id_especialidade_1",
											"id_especialidade_3"
										],
										"instagram": "perfil_instagram_atualizado",
										"email": "novo_email@clinica.com",
										"whatsapp": "+55 11 9876-5432",
										"descricao": "Descrição atualizada da clínica",
										"endereco": "id_endereco_atualizado"
									}
								}
							}
						}
					}
				},
				"responses": {
					"201": {
						"description": "Clínica atualizada com sucesso",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Clinica"
								},
								"examples": {
									"clinica": {
										"value": {
											"cep": "00000-000",
											"rua": "rua x",
											"numero": 123,
											"bairro": "bairro x",
											"cidade": "cidade x",
											"uf": "xx",
											"nome": "Clinica X Atualizada",
											"imagem": "url_da_imagem_atualizada",
											"horarioSemana": {
												"open": "09:00",
												"close": "18:00"
											},
											"Sabado": {
												"open": "10:00",
												"close": "14:00"
											},
											"longitude": -43.123456,
											"latitude": -22.987654,
											"especialidades": [
												"id_especialidade_1",
												"id_especialidade_3"
											],
											"instagram": "perfil_instagram_atualizado",
											"email": "novo_email@clinica.com",
											"whatsapp": "+55 11 9876-5432",
											"descricao": "Descrição atualizada da clínica",
											"endereco": "id_endereco_atualizado"
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "Campos inválidos ou nome muito curto",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										},
										"Errors": {
											"type": "array",
											"items": {
												"type": "string"
											}
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno do servidor",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/admin/deletar-clinica/{id}": {
			"delete": {
				"summary": "Deletar Clínica",
				"description": "Essa rota será responsável por deletar uma clínica existente",
				"tags": ["Clinicas"],
				"security": [
					{
						"bearerAuth": []
					}
				],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"description": "ID da clínica a ser deletada"
					}
				],
				"responses": {
					"204": {
						"description": "no content"
					},
					"500": {
						"description": "Erro interno do servidor",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										}
									}
								}
							}
						}
					}
				}
			}
		},

		"/clinicas": {
			"get": {
				"summary": "Listar Clínicas",
				"description": "Essa rota será responsável por listar todas as clínicas",
				"tags": ["Clinicas"],
				"responses": {
					"200": {
						"description": "Lista de clínicas",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/Clinica"
									}
								},
								"examples": {
									"clinicas": {
										"value": [
											{
												"nome": "Clinica x",
												"imagem": "url_da_imagem_A",
												"horarioSemana": {
													"open": "08:00",
													"close": "17:00"
												},
												"Sabado": {
													"open": "09:00",
													"close": "13:00"
												},
												"longitude": -43.123456,
												"latitude": -22.987654,
												"especialidades": [
													"id_especialidade_1",
													"id_especialidade_2"
												],
												"instagram": "perfil_instagram_A",
												"email": "email@clinicaA.com",
												"whatsapp": "+55 11 1234-5678",
												"descricao": "Descrição da clínica A",
												"endereco": "id_endereco_A"
											},
											{
												"nome": "Clinica B",
												"imagem": "url_da_imagem_B",
												"horarioSemana": {
													"open": "09:00",
													"close": "18:00"
												},
												"Sabado": {
													"open": "10:00",
													"close": "14:00"
												},
												"longitude": -43.654321,
												"latitude": -22.123456,
												"especialidades": [
													"id_especialidade_2",
													"id_especialidade_3"
												],
												"instagram": "perfil_instagram_B",
												"email": "email@clinicaB.com",
												"whatsapp": "+55 11 9876-5432",
												"descricao": "Descrição da clínica B",
												"endereco": {
													"value": {
														"cep": "00000-000",
														"rua": "rua x",
														"numero": 123,
														"bairro": "bairro x",
														"cidade": "cidade x",
														"uf": "xx"
													}
												}
											}
										]
									}
								}
							}
						}
					},
					"404": {
						"description": "Nenhuma clínica encontrada"
					},
					"500": {
						"description": "Erro interno do servidor",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/clinica/{nome}": {
			"get": {
				"summary": "Filtrar Clínica por Nome",
				"description": "Essa rota será responsável por filtrar uma clínica por nome",
				"tags": ["Clinicas"],
				"parameters": [
					{
						"name": "nome",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"description": "Nome da clínica a ser filtrada"
					}
				],
				"responses": {
					"200": {
						"description": "Clínica filtrada pelo nome",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Clinica"
								},
								"examples": {
									"clinica": {
										"value": {
											"nome": "Clinica A",
											"imagem": "url_da_imagem_A",
											"horarioSemana": {
												"open": "08:00",
												"close": "17:00"
											},
											"Sabado": {
												"open": "09:00",
												"close": "13:00"
											},
											"longitude": -43.123456,
											"latitude": -22.987654,
											"especialidades": [
												"id_especialidade_1",
												"id_especialidade_2"
											],
											"instagram": "perfil_instagram_A",
											"email": "email@clinicaA.com",
											"whatsapp": "+55 11 1234-5678",
											"descricao": "Descrição da clínica A",
											"endereco": "id_endereco_A"
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Clínica não encontrada"
					},
					"500": {
						"description": "Erro interno do servidor",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										}
									}
								}
							}
						}
					}
				}
			}
		},

		"/admin/novo-hospital": {
			"post": {
				"summary": "Cadastrar Hospital",
				"description": "Essa rota será responsável por cadastrar um hospital",
				"tags": ["Hospitais"],
				"security": [
					{
						"bearerAuth": []
					}
				],
				"requestBody": {
					"description": "Dados do Hospital",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/Hospital"
							},
							"examples": {
								"clinica": {
									"value": {
										"cep": "00000-000",
										"rua": "rua x",
										"numero": 123,
										"bairro": "bairro x",
										"cidade": "cidade x",
										"uf": "xx",
										"nome": "Hospital x",
										"imagem": "url_da_imagem",
										"horarioSemana": {
											"open": "08:00",
											"close": "17:00"
										},
										"Sabado": {
											"open": "09:00",
											"close": "13:00"
										},
										"longitude": -43.123456,
										"latitude": -22.987654,
										"especialidades": [
											"id_especialidade_1",
											"id_especialidade_2"
										],
										"instagram": "perfil_instagram",
										"email": "emailhospital.com",
										"whatsapp": "+55 11 1234-5678",
										"descricao": "Descrição do hospital"
									}
								}
							}
						}
					}
				},
				"responses": {
					"201": {
						"description": "Hospital cadastrado com Sucesso!",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Hospital"
								}
							}
						}
					},
					"400": {
						"description": "Campos inválidos ou nome muito curto",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										},
										"Errors": {
											"type": "array",
											"items": {
												"type": "string"
											}
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno do servidor",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/admin/alterar-hospital/{id}": {
			"put": {
				"summary": "Alterar Hospital",
				"description": "Essa rota será responsável por alterar um hospital existente",
				"tags": ["Hospitais"],
				"security": [
					{
						"bearerAuth": []
					}
				],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"description": "ID do hospital a ser alterado"
					}
				],
				"requestBody": {
					"description": "Dados atualizados do Hospital",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/Hospital"
							},
							"examples": {
								"clinica": {
									"value": {
										"cep": "00000-000",
										"rua": "rua x",
										"numero": 123,
										"bairro": "bairro x",
										"cidade": "cidade x",
										"uf": "xx",
										"nome": "Hospital x",
										"imagem": "url_da_imagem",
										"horarioSemana": {
											"open": "08:00",
											"close": "17:00"
										},
										"Sabado": {
											"open": "09:00",
											"close": "13:00"
										},
										"longitude": -43.123456,
										"latitude": -22.987654,
										"especialidades": [
											"id_especialidade_1",
											"id_especialidade_2"
										],
										"instagram": "perfil_instagram",
										"email": "emailhospital.com",
										"whatsapp": "+55 11 1234-5678",
										"descricao": "Descrição do hospital"
									}
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Hospital alterado com sucesso",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Hospital"
								}
							}
						}
					},
					"400": {
						"description": "Campos inválidos ou nome muito curto",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										},
										"Errors": {
											"type": "array",
											"items": {
												"type": "string"
											}
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Hospital não encontrado",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno do servidor",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/admin/deletar-hospital/{id}": {
			"delete": {
				"summary": "Deletar Hospital",
				"description": "Essa rota será responsável por deletar um hospital existente",
				"tags": ["Hospitais"],
				"security": [
					{
						"bearerAuth": []
					}
				],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"description": "ID do hospital a ser deletado"
					}
				],
				"responses": {
					"204": {
						"description": "Hospital deletado com sucesso"
					},
					"404": {
						"description": "Hospital não encontrado",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno do servidor",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/hospitais": {
			"get": {
				"summary": "Listar Hospitais",
				"description": "Essa rota será responsável por listar todos os hospitais",
				"tags": ["Hospitais"],
				"responses": {
					"200": {
						"description": "Lista de hospitais",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/Hospital"
									}
								},
								"examples": {
									"hospitais": {
										"value": [
											{
												"nome": "Hospital x",
												"imagem": "url_da_imagem_A",
												"horarioSemana": {
													"open": "08:00",
													"close": "17:00"
												},
												"Sabado": {
													"open": "09:00",
													"close": "13:00"
												},
												"longitude": -43.123456,
												"latitude": -22.987654,
												"especialidades": [
													"id_especialidade_1",
													"id_especialidade_2"
												],
												"email": "email@hospitalA.com",
												"whatsapp": "+55 11 1234-5678",
												"descricao": "Descrição do Hospital A",
												"endereco": "id_endereco_A"
											},
											{
												"nome": "Hospital B",
												"imagem": "url_da_imagem_B",
												"horarioSemana": {
													"open": "09:00",
													"close": "18:00"
												},
												"Sabado": {
													"open": "10:00",
													"close": "14:00"
												},
												"longitude": -43.654321,
												"latitude": -22.123456,
												"especialidades": [
													"id_especialidade_2",
													"id_especialidade_3"
												],
												"email": "email@hospitalB.com",
												"whatsapp": "+55 11 9876-5432",
												"descricao": "Descrição do Hospital B",
												"endereco": {
													"value": {
														"cep": "00000-000",
														"rua": "rua x",
														"numero": 123,
														"bairro": "bairro x",
														"cidade": "cidade x",
														"uf": "xx"
													}
												}
											}
										]
									}
								}
							}
						}
					},
					"500": {
						"description": "Erro interno do servidor",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"Message": {
											"type": "string"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/buscar": {
			"get": {
			  "summary": "Buscar Consultas por Nome",
			  "description": "Esta rota busca consultas médicas por nome.",
			  "tags": ["Consultas"],
			  "parameters": [
				{
				  "name": "nome",
				  "in": "query",
				  "description": "Nome da consulta a ser buscada.",
				  "required": true,
				  "schema": {
					"type": "string"
				  }
				}
			  ],
			  "responses": {
				"200": {
				  "description": "Consultas encontradas com sucesso.",
				  "content": {
					"application/json": {
					  "schema": {
						"$ref": "#/components/schemas/Consultas"
					  }
					}
				  }
				},
				"400": {
				  "description": "Campos inválidos ou nome muito curto.",
				  "content": {
					"application/json": {
					  "schema": {
						"type": "object",
						"properties": {
						  "Message": {
							"type": "string"
						  },
						  "Errors": {
							"type": "array",
							"items": {
							  "type": "string"
							}
						  }
						}
					  }
					}
				  }
				},
				"500": {
				  "description": "Erro interno do servidor.",
				  "content": {
					"application/json": {
					  "schema": {
						"type": "object",
						"properties": {
						  "Message": {
							"type": "string"
						  }
						}
					  }
					}
				  }
				}
			  }
			}
		  },
		  "/unidades-de-saude": {
			"get": {
			  "summary": "Listar Unidades de Saúde",
			  "description": "Esta rota lista unidades de saúde.",
			  "tags": ["Consultas"],
			  "responses": {
				"200": {
				  "description": "Unidades de saúde listadas com sucesso.",
				  "content": {
					"application/json": {
					  "schema": {
						"$ref": "#/components/schemas/Consultas"
					  }
					}
				  }
				},
				"500": {
				  "description": "Erro interno do servidor.",
				  "content": {
					"application/json": {
					  "schema": {
						"type": "object",
						"properties": {
						  "Message": {
							"type": "string"
						  }
						}
					  }
					}
				  }
				}
			  }
			}
		  },
		 
		  "/especialidades/{nome}": {
			"get": {
			  "summary": "Buscar Especialidades por Nome da Unidade de Saúde",
			  "description": "Esta rota busca especialidades médicas pelo nome da unidade de saúde.",
			  "tags": ["Consultas"],
			  "parameters": [
				{
				  "name": "nome",
				  "in": "path",
				  "description": "Nome da unidade de saúde para buscar especialidades.",
				  "required": true,
				  "schema": {
					"type": "string"
				  }
				}
			  ],
			  "responses": {
				"200": {
				  "description": "Especialidades encontradas com sucesso.",
				  "content": {
					"application/json": {
					  "schema": {
						"$ref": "#/components/schemas/Consultas"
					  }
					}
				  }
				},
				"404": {
				  "description": "Nenhuma especialidade encontrada para o nome fornecido.",
				  "content": {
					"application/json": {
					  "schema": {
						"type": "object",
						"properties": {
						  "Message": {
							"type": "string"
						  }
						}
					  }
					}
				  }
				},
				"500": {
				  "description": "Erro interno do servidor.",
				  "content": {
					"application/json": {
					  "schema": {
						"type": "object",
						"properties": {
						  "Message": {
							"type": "string"
						  }
						}
					  }
					}
				  }
				}
			  }
			}
		  },
		  "/unidade-de-saude/{nome}": {
			"get": {
			  "summary": "Buscar Unidade de Saúde por Nome",
			  "description": "Esta rota busca uma unidade de saúde por nome.",
			  "tags": ["Consultas"],
			  "parameters": [
				{
				  "name": "nome",
				  "in": "path",
				  "description": "Nome da unidade de saúde a ser buscada.",
				  "required": true,
				  "schema": {
					"type": "string"
				  }
				}
			  ],
			  "responses": {
				"200": {
				  "description": "Unidade de saúde encontrada com sucesso.",
				  "content": {
					"application/json": {
					  "schema": {
						"$ref": "#/components/schemas/Consultas"
					  }
					}
				  }
				},
				"500": {
				  "description": "Erro interno do servidor.",
				  "content": {
					"application/json": {
					  "schema": {
						"type": "object",
						"properties": {
						  "Message": {
							"type": "string"
						  }
						}
					  }
					}
				  }
				}
			  }
			}
		  },
		  "/total-unidades-de-saude": {
			"get": {
			  "summary": "Obter Total de Unidades de Saúde",
			  "description": "Esta rota retorna o total de unidades de saúde.",
			  "tags": ["Consultas"],
			  "responses": {
				"200": {
				  "description": "Total de unidades de saúde obtido com sucesso.",
				  "content": {
					"application/json": {
					  "schema": {
						"type": "object",
						"properties": {
						  "total": {
							"type": "integer"
						  }
						}
					  }
					}
				  }
				},
				"500": {
				  "description": "Erro interno do servidor.",
				  "content": {
					"application/json": {
					  "schema": {
						"type": "object",
						"properties": {
						  "error": {
							"type": "string"
						  }
						}
					  }
					}
				  }
				}
			  }
			}
		  },
		  "/pedidos": {
			"get": {
			  "summary": "Listar Unidades de Saúde Pendentes",
			  "description": "Esta rota lista unidades de saúde com pedidos pendentes.",
			  "tags": ["Consultas"],
			  "responses": {
				"200": {
				  "description": "Unidades de saúde com pedidos pendentes listadas com sucesso.",
				  "content": {
					"application/json": {
					  "schema": {
						"type": "object",
						"properties": {
						  "Message": {
							"type": "string"
						  }
						}
					  }
					}
				  }
				},
				"500": {
				  "description": "Erro interno do servidor.",
				  "content": {
					"application/json": {
					  "schema": {
						"type": "object",
						"properties": {
						  "error": {
							"type": "string"
						  }
						}
					  }
					}
				  }
				}
			  }
			}
		  }
	},
	"components": {
		"schemas": {
			"Login": {
				"type": "object",
				"properties": {
					"email": {
						"type": "string"
					},
					"senha": {
						"type": "string"
					}
				},
				"required": ["email", "senha"]
			},
			"Usuario": {
				"type": "object",
				"properties": {
					"nome": {
						"type": "string"
					},
					"email": {
						"type": "string"
					},
					"senha": {
						"type": "string"
					}
				},
				"required": ["nome", "email", "senha"]
			},
			"Senha": {
				"type": "object",
				"properties": {
				  "senha": {
					"type": "string"
				  },
				  "confirmarSenha": {
					"type": "string"
				  }
				},
				"required": ["senha", "confirmarSenha"]
			  },
			  "UnidadeDeSaude": {
				"type": "object",
				"properties": {
				  "nome": {
					"type": "string"
				  },
				  "endereco": {
					"type": "string"
				  }
				},
				"required": ["nome", "endereco"]
			  },
			"Clinica": {
				"type": "object",
				"properties": {
					"nome": {
						"type": "string"
					},
					"imagem": {
						"type": "string"
					},
					"horarioSemana": {
						"type": "object",
						"properties": {
							"open": {
								"type": "string"
							},
							"close": {
								"type": "string"
							}
						}
					},
					"Sabado": {
						"type": "object",
						"properties": {
							"open": {
								"type": "string"
							},
							"close": {
								"type": "string"
							}
						}
					},
					"longitude": {
						"type": "number"
					},
					"latitude": {
						"type": "number"
					},
					"especialidades": {
						"type": "array",
						"items": {
							"type": "string"
						}
					},
					"instagram": {
						"type": "string"
					},
					"email": {
						"type": "string"
					},
					"whatsapp": {
						"type": "string"
					},
					"descricao": {
						"type": "string"
					},

					"cep": {
						"type": "string"
					},
					"rua": {
						"type": "string"
					},
					"numero": {
						"type": "string"
					},
					"bairro": {
						"type": "string"
					},
					"cidade": {
						"type": "string"
					},
					"uf": {
						"type": "string"
					}
				},
				"required": [
					"nome",
					"horarioSemana",
					"Sabado",
					"longitude",
					"latitude",
					"especialidades",
					"cep",
					"rua",
					"numero",
					"bairro",
					"cidade",
					"uf"
				]
			},
			"Hospital": {
				"type": "object",
				"properties": {
					"nome": {
						"type": "string"
					},
					"imagem": {
						"type": "string"
					},
					"horarioSemana": {
						"type": "object",
						"properties": {
							"open": {
								"type": "string"
							},
							"close": {
								"type": "string"
							}
						}
					},
					"Sabado": {
						"type": "object",
						"properties": {
							"open": {
								"type": "string"
							},
							"close": {
								"type": "string"
							}
						}
					},
					"longitude": {
						"type": "number"
					},
					"latitude": {
						"type": "number"
					},
					"especialidades": {
						"type": "array",
						"items": {
							"type": "string"
						}
					},
					"email": {
						"type": "string"
					},
					"whatsapp": {
						"type": "string"
					},
					"cep": {
						"type": "string"
					},
					"rua": {
						"type": "string"
					},
					"numero": {
						"type": "string"
					},
					"bairro": {
						"type": "string"
					},
					"cidade": {
						"type": "string"
					},
					"uf": {
						"type": "string"
					}
				},
				"required": [
					"nome",
					"longitude",
					"latitude",
					"especialidades",
					"cep",
					"rua",
					"numero",
					"bairro",
					"cidade",
					"uf"
				]
			},
			"Consultas": {
				"type": "object",
				"description": "Este caminho contém operações para gerenciar consultas médicas relacionadas tanto a Clínicas como Hospitais.",
				"properties": {
					"id": {
						"type": "integer"
					},
					"nome": {
						"type": "string"
					},
					"descricao": {
						"type": "string"
					}
				}
			}
		},
		"securitySchemes": {
			"bearerAuth": {
				"type": "http",
				"scheme": "bearer",
				"bearerFormat": "JWT"
			}
		}
	}
}
